apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: bootcamp
spec:
  containers:
  - name: web
    image: caddy:2.8-alpine
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "128Mi"
      requests:
        memory: "64Mi"
        cpu: "10m"
